Publish-BGEO-cache-using-the-existing-frames
ynput/ayon-houdini pull request #154
Opened 2024-11-02 09:45 UTC by krishnaavril

## Changelog Description
Publish using the existing frames in houdini BGEO

## Testing notes:
1. When creating added boolean parameter for using the existing frames
2. when publishing if the node is turned on-> it should skip the render and use the existing frames
3. If the node is turned off-> It should render without any issues

2024-11-02 14:40 UTC, BigRoy requested changes
Unfortunately this is the wrong approach - we should unify it with the other render options of other instances so they behave the same - instead of making this separate unique behavior.

As such, this should instead become an `EnumOption` that allows you to pick from:
- Local render
- Local use existing frames
- Farm render
- Farm use existing frames
- etc.

2024-11-06 14:34 UTC, krishnaavril commented
Hello!

After Roy's feedback, I changed the method and approach similar to the other logic, It is working fine for the below 3 methods:

1. Local render
2. Local use existing frames
3. Farm render

Please validate the code @BigRoy  @MustafaJafar 

Can you guys hint where we need to tweak and skip the caching for the "Farm use existing frames" working method?
Appreciate your time!

2024-11-06 21:57 UTC, BigRoy commented on client/ayon_houdini/plugins/publish/extract_rop.py
> +            print("Skipping Houdini local render...")
```suggestion
        creator_attributes = instance.data["creator_attributes"]
        if creator_attributes.get("render_target") == "local_no_render":
            self.log.debug(
                "Skipping ROP render to use existing frames"
                f" for instance: {instance}")
        else:
            self.render_rop(instance)
```

2024-11-06 21:59 UTC, BigRoy commented on client/ayon_houdini/plugins/publish/collect_cache_farm.py
> +        farm_enabled = False if farm_enabled in ["local", "local_no_render"] else farm_enabled
```suggestion
        render_target: str = creator_attribute.get("render_target")
        # Determine settings based on render_target value
        farm_enabled = render_target in {"farm", "farm_no_render"}
```

2024-11-07 10:03 UTC, BigRoy commented on client/ayon_houdini/plugins/create/create_bgeo.py
> +            "farm_no_render": "Use existing frames (farm)"
I'm pretty sure we'll need matching PRs on `ayon-deadline` to support this. @MustafaJafar thoughts?

I do like the feature though.

2024-11-08 03:26 UTC, krishnaavril commented
The same technique must also be used in the vdb cache as well

2024-11-20 15:52 UTC, MustafaJafar commented
Hello @krishnaavril,
Many thank for your contribution. and in turn I've created another PR https://github.com/ynput/ayon-houdini/pull/180 to support publishing Bgeos with different render targets. 
It reuses some of the logic of render instances. 

IMO, supporting more different render targets like `"farm_no_render": "Use existing frames (farm)"` should have a separate issue.

2024-11-22 07:59 UTC, closed without merging